name: Build Docker Image

on:
  pull_request:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: write # to push to registry 
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      if: github.event_name == 'pull_request'
      run: docker build -t ics-outlook-proxy .

    - name: Login to Docker 
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      if: github.event_name == 'push'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/ics-outlook-proxy:latest
